# -*- coding: utf-8 -*-
"""ML1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162qD8J3Oyo4Ku0Bulg36zMa5_9IEpN4d
"""

import pandas as pd
import numpy as np
from sklearn import metrics
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

data = pd.read_csv("/content/uber.csv")

data.head()

data.tail()

data.info()

data.describe()

data.shape

data.columns

data = data.drop(['Unnamed: 0', 'key'], axis=1)

data.head()

data['months'] = data['pickup_datetime']
data['hours'] = data['pickup_datetime']
data['months'] = data['months'].str.slice(start=5,stop=7)
data['hours'] = data['hours'].str.slice(start=11, stop=13)

data.head()

data = data.drop('pickup_datetime', axis=1)
data

# Alternate to datetime separation
# df = pd.read_csv("/content/uber.csv")
# df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])
# df['hour'] = df['pickup_datetime'].dt.hour
# df['day'] = df['pickup_datetime'].dt.dayofweek
# df['month'] = df['pickup_datetime'].dt.month
# df = df.drop(columns=['pickup_datetime'])
# df

data.isnull().sum()

data['dropoff_latitude'] = data['dropoff_latitude'].fillna(data['dropoff_latitude'].mean())
data['dropoff_longitude'] = data['dropoff_longitude'].fillna(data['dropoff_longitude'].mean())
data.isnull().sum()

data.describe()

data.replace(to_replace=0, value = data['passenger_count'].mean(), inplace=True)
data[data['fare_amount']<=0] = data['fare_amount'].mean()
data.describe()

data.plot(kind="box", subplots=True, layout=(6,2), figsize=(15,20))

def remove_outlier(df1, col):
  Q1 = df1[col].quantile(0.25)
  Q3 = df1[col].quantile(0.75)
  IQR = Q3-Q1
  lb = Q1 - 1.5*IQR
  ub = Q3 + 1.5*IQR
  data[col] = np.clip(df1[col], lb, ub)
  return df1

def treat_outliers_all(df1, colslist):
  for col in colslist:
    remove_outlier(df1, col)
  return df1

data.columns

cols = ['fare_amount', 'pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude', 'passenger_count']
treat_outliers_all(data, cols)

data.plot(kind="box", subplots=True, layout=(6,2), figsize=(15,20))

data.shape

data.isnull().sum()

plt.scatter(data['pickup_latitude'],data['fare_amount'])
plt.xlabel("pickup_latitude")
plt.ylabel("fare_amount")

plt.scatter(data['pickup_longitude'],data['fare_amount'])
plt.xlabel("pickup_longitude")
plt.ylabel("fare_amount")

plt.scatter(data['dropoff_latitude'],data['fare_amount'])
plt.xlabel("dropoff_latitude")
plt.ylabel("fare_amount")

plt.scatter(data['dropoff_longitude'],data['fare_amount'])
plt.xlabel("dropoff_longitude")
plt.ylabel("fare_amount")

corr_matrix = data.corr()
corr_matrix

sns.heatmap(corr_matrix, annot=True)

data.columns

X = data.iloc[:,1:]
y = data.iloc[:,0]

# OR
# features = ['pickup_longitude', 'pickup_latitude',
#             'dropoff_longitude', 'dropoff_latitude', 'passenger_count', 'hour', 'month', 'day']
# X = df[features]
# y = df['fare_amount']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=42)
print(X_train.shape, y_train.shape, X_test.shape, y_test.shape)

lr = LinearRegression()
lr.fit(X_train, y_train)
lr.score(X_test,y_test)

y_pred = lr.predict(X_test)
result = pd.DataFrame()
result['Actual'], result['Predicted'] = y_test, y_pred
result.sample(10)

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R Squared (R²):', np.sqrt(metrics.r2_score(y_test, y_pred)))

rf = RandomForestRegressor(n_estimators=10, random_state=42)
rf.fit(X_train, y_train)
rf.score(X_test,y_test)

y_pred = rf.predict(X_test)
result1 = pd.DataFrame()
result1['Actual'], result1['Predicted'] = y_test, y_pred
result1.sample(10)

print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))
print('R Squared (R²):', np.sqrt(metrics.r2_score(y_test, y_pred)))

