# -*- coding: utf-8 -*-
"""ML_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kLZVj4H1povTiIEJHVqYGXjqjWBSehMo
"""

import pandas as pd
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, ConfusionMatrixDisplay, precision_score, recall_score
import time
import matplotlib.pyplot as plt

data = pd.read_csv("emails.csv")

data

data.head()

data.shape

data = data.drop('Email No.',axis=1)

data.shape

data.describe()

data.info()

data['Prediction'].value_counts()

X = data.drop('Prediction', axis=1)
y = data['Prediction']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 42)

from sklearn.neighbors import KNeighborsClassifier
start = time.time()
neigh = KNeighborsClassifier(n_neighbors=2)
neigh.fit(X_train, y_train)

y_pred = neigh.predict(X_test)
knn_time = time.time() - start
knn_acc= accuracy_score(y_test, y_pred)

print("\n************** K-Nearest Neighbors ****************\n")
print(f"Training time: {knn_time}s")
print(f"Accuracy: {knn_acc}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

neigh.score(X_train, y_train)
neigh.score(X_test, y_test)

print("Confusion Matrix: ")
cm = confusion_matrix(y_test, y_pred)
cm

mat = ConfusionMatrixDisplay(confusion_matrix = cm)
mat.plot()
plt.show()

print("accuracy_score: ")
accuracy_score(y_test, y_pred)

print("precision_score: ")
precision_score(y_test, y_pred)

print("recall_score: ")
recall_score(y_test, y_pred)

print("Error: ")
1-accuracy_score(y_test, y_pred)

from sklearn.svm import SVC
start = time.time()
svm = SVC(kernel = 'linear', random_state=42)
svm.fit(X_train, y_train)

y_pred = svm.predict(X_test)
svm_time = time.time()-start
svm_acc= accuracy_score(y_test, y_pred)

print(f"Training time: {svm_time}s")
print(f"Accuracy: {svm_acc}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

svm.score(X_train, y_train)
svm.score(X_test, y_test)

print("Confusion Matrix: ")
cm = confusion_matrix(y_test, y_pred)
cm

mat = ConfusionMatrixDisplay(confusion_matrix = cm)
mat.plot()
plt.show()

