# -*- coding: utf-8 -*-
"""ML_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BStIQvtJUzq7zBH98O1bGhyTzJhG5QZO
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.cluster import KMeans

df = pd.read_csv('/content/sales_data_sample.csv',encoding='latin')
df.head()

df.describe()

df.info()

df['STATUS'] = LabelEncoder().fit_transform(df['STATUS'])
df['DEALSIZE'] = LabelEncoder().fit_transform(df['DEALSIZE'])
df.info()

df.columns

features = [
    'QUANTITYORDERED', 'PRICEEACH', 'SALES', 'MSRP',
    'ORDERLINENUMBER', 'QTR_ID', 'MONTH_ID', 'YEAR_ID',
    'STATUS', 'DEALSIZE'
]
X = df[features]
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Elbow method to find optimal number of clusters
inertias = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(X_scaled)
    inertias.append(kmeans.inertia_)

# Plot the elbow curve
plt.plot(range(1, 11), inertias, marker='o')
plt.title('Elbow Method for Optimal Clusters')
plt.xlabel('Number of clusters')
plt.ylabel('Inertia')
plt.grid(True)
plt.show()

# Fit KMeans with chosen number of clusters (e.g., 3)
kmeans = KMeans(n_clusters=3, random_state=42)
df['Cluster'] = kmeans.fit_predict(X_scaled)

# View sample results
print(df[['QUANTITYORDERED', 'PRICEEACH', 'SALES', 'MSRP', 'Cluster']].head())

plt.figure(figsize=(8,6))
plt.scatter(df['PRICEEACH'], df['SALES'], c=df['Cluster'], cmap='viridis', s=50)
plt.title('Customer Segments based on SALES and PRICEEACH')
plt.xlabel('SALES')
plt.ylabel('PRICEEACH')
plt.colorbar(label='Cluster')
plt.show()

